### ISSUE TITLE
Ne fonctionne pas avec la dernière version de Dotclear

### ISSUE THREAD

**Issue by franck-tomek** [nikrou/externalLinks#1]
Ça date de plus longtemps d'après le forum, mais mon test sur la dernière version de Dotclear (2.22) s'est révélé peu concluant, le plugin ne semble pas fonctionner.

**Comment by nikrou** [comment]
Je veux bien des détails sur ce qui ne fonctionne pas, ici ou par mail.

**Comment by franck-tomek** [comment]
Ah, je viens de retester. Petit détail qui a son importance : ça fonctionne si on n'ajoute pas l'icône, par contre avec l'icône, ça ouvre le lien dans le même onglet.
